services:
  - type: web
    name: springboot-escalab-backend
    runtime: docker
    plan: free
    healthCheckPath: /v3/api-docs
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: CLIENT_SECRET
        sync: false
      - key: PORT
        value: "8080"
